### ISSUE TITLE
Middleware should do the right thing with X-Sandstorm-Username

### ISSUE THREAD

**Issue by phildini** [phildini/django-sandstorm#1]
Right now, the middleware correctly creates-and-authenticates a user when it finds the `X-Sandstorm-User-Id` header. This is great! 

It should also (optionally?) set the `user.first_name` field to `X-Sandstorm-Username`.

@paulproteus, thoughts?

**Comment by paulproteus** [comment]
I think that is an excellent plan. I also think that clobbering the existing `request.user.first_name` is A-OK.

**Comment by phildini** [comment]
This is done!
